/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "miner.h"

int *
gettransactionid_100_svc(args *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
getchallenge_100_svc(args *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
gettransactionstatus_100_svc(args *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
getwinner_100_svc(args *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

TransactionInfo *
getseed_100_svc(args *argp, struct svc_req *rqstp)
{
	static TransactionInfo  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
submitchallenge_100_svc(args *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
