/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINER_H_RPCGEN
#define _MINER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	int tid;
	int cid;
	char *seed;
};
typedef struct args args;

#define PROG 5555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define GETTRANSACTIONID 1
extern  int * gettransactionid_100(args *, CLIENT *);
extern  int * gettransactionid_100_svc(args *, struct svc_req *);
#define GETCHALLENGE 2
extern  int * getchallenge_100(args *, CLIENT *);
extern  int * getchallenge_100_svc(args *, struct svc_req *);
#define GETTRANSACTIONSTATUS 3
extern  int * gettransactionstatus_100(args *, CLIENT *);
extern  int * gettransactionstatus_100_svc(args *, struct svc_req *);
#define GETWINNER 4
extern  int * getwinner_100(args *, CLIENT *);
extern  int * getwinner_100_svc(args *, struct svc_req *);
#define GETSEED 5
extern  TransactionInfo * getseed_100(args *, CLIENT *);
extern  TransactionInfo * getseed_100_svc(args *, struct svc_req *);
#define SUBMITCHALLENGE 6
extern  int * submitchallenge_100(args *, CLIENT *);
extern  int * submitchallenge_100_svc(args *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETTRANSACTIONID 1
extern  int * gettransactionid_100();
extern  int * gettransactionid_100_svc();
#define GETCHALLENGE 2
extern  int * getchallenge_100();
extern  int * getchallenge_100_svc();
#define GETTRANSACTIONSTATUS 3
extern  int * gettransactionstatus_100();
extern  int * gettransactionstatus_100_svc();
#define GETWINNER 4
extern  int * getwinner_100();
extern  int * getwinner_100_svc();
#define GETSEED 5
extern  TransactionInfo * getseed_100();
extern  TransactionInfo * getseed_100_svc();
#define SUBMITCHALLENGE 6
extern  int * submitchallenge_100();
extern  int * submitchallenge_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINER_H_RPCGEN */
